### PR TITLE
Plantcv adding spice functionality

### PR DESCRIPTION
**Pull request by CJRobey**
Title: This pull request is an attempt to add SPICE to the plantCV repository

### Description
Describe your changes, for example:
* What did you change/add and why?
- Added the entire SPICE repository with the correct commenting formatting outlined by the CONTRIBUTIONS document. 
- Added SPICE into the proper __init__.py files so that it would integrate properly in the overall build. -- - Included cvxopt python package in the setup.py and requirements.txt files
- Created one unit test at the end of the tests/tests.py file. This connected to a new .npz file that I created to benchmark the unit test.

* Have you tested the changes, and if so, how?
- Yes, I rebuilt the entire repository and tested using '''py.test tests/tests.py''' with the new unit test integrated.
- I don't think that I have moved documentation in the proper folders yet.

### Types of changes
This is a new feature that does not change any of the existing functionality.

### Checklist:

- [ x ] Relevant tests (and test data) have been added or updated and passed.
- [ x ] The documentation was added or updated.
- [ N/A ] Relevant issues were updated or added.

### CODE REVIEW

**Comment by nfahlgren** [comment]
Hi @CJRobey, it looks like tests passed in Python 3.6 but not 2.7, do you think SPICE will only work in 3+?

If so, I am proposing we drop Python 2 support for the `hyperspectral` PlantCV package. My reasoning is:

1. The PlantCV `hyperspectral` package is new, so there are no prior expectations about dependencies.
2. PlantCV supports both Python 2.7 and 3+ but at some point we will have to drop 2.7 support anyhow.
3. The `hyperspectral` package is an optional add-on, so anyone who really wants to use PlantCV with Python 2.7 can forgo installing it.
4. Building the `hyperspectral` package in Python 3 from the ground up will make our lives easier!

Thoughts @maliagehan?

**Comment by CJRobey** [comment]
Hey Noah! 

I'm actually not exactly sure what fails. Let me take a look into it to see if I can fix the issue. Otherwise, it may be a good idea to move into Python 3 directly since there are a few common functions and syntax preferences that are not supported in Python 2.

Thanks,
Caleb

**Comment by CJRobey** [comment]
Also, would you like me to add a unit test for the demo? Or even keep it in the folder?

**Comment by nfahlgren** [comment]
Hi @CJRobey, sorry for the delay. If you click on the Details link next to the continuous-integration/travis-ci check and click through a few more things you can get to the build log to see what passed/failed. Here's a direct link to the Python 2.7 build job though: https://travis-ci.org/danforthcenter/plantcv-hyperspectral/jobs/449348926

It looks like the specific error is:

```
    import plantcv.hyperspectral as hy
plantcv/hyperspectral/__init__.py:7: in <module>
    from plantcv.hyperspectral import SPICE
plantcv/hyperspectral/SPICE/__init__.py:1: in <module>
    from plantcv.hyperspectral.SPICE.SPICE import SPICE
E     File "/home/travis/build/danforthcenter/plantcv-hyperspectral/plantcv/hyperspectral/SPICE/SPICE.py", line 114
E       endmembers = (np.linalg.inv(P.T@P + lamb*(Im - (I1@I1.T)/M)) @ (P.T @ X.T)).T
E                                      ^
E   SyntaxError: invalid syntax
```

But yeah, I'm leaning towards just eliminating Python 2 for this package for simplicity.

I think the tests look good right now!

**Comment by CJRobey** [comment]
These issues should be rectified now Noah. Sorry for the very delayed response - I've had a crazy week. "np.dot" is a less clean looking but totally equivalent implementation of "@"

**Comment by nfahlgren** [comment]
Hi @CJRobey, no worries! What do you think about rolling back to what you had before? I have a pull request queued up to remove Python 2 support for this package which would solve the previous build issue.

**Comment by CJRobey** [comment]
I just rolled it back! That sounds good to me. I think that a lot of issues will be avoided in the long term by removing Python 2 support, so solid call.

**Review by nfahlgren — APPROVED** [review]
Thanks @CJRobey!

**Pull request merged**
