### PR TITLE
Hypernormal

### PR DESCRIPTION
**Pull request by Sanazjd**
new hyper spectral functions

### CODE REVIEW

**Review by maliagehan — APPROVED** [review]

**Comment by nfahlgren** [comment]
@Sanazjd looks like we need to add `osgeo` to `requirements.txt`

**Comment by Sanazjd** [comment]
> @Sanazjd looks like we need to add `osgeo` to `requirements.txt`

I just added.

**Comment by nfahlgren** [comment]
Oops, I forgot that the package that provides osgeo is GDAL, so that should be in requirements instead

**Comment by nfahlgren** [comment]
@Sanazjd I finally got the C and Python GDAL packages to talk to each other!

There are some errors in the build log (https://travis-ci.org/danforthcenter/plantcv-hyperspectral/jobs/516307250). It looks like it doesn't like this:

```python
gdalhyper = gdal.Open(path)
wavelength = gdalhyper.GetRasterBand(1)
```

`AttributeError: 'NoneType' object has no attribute 'GetRasterBand'`

One possibility is that this is a feature of GDAL v2+ and the Travis CI environment, using Ubuntu, is installing GDAL 1.11. If that is the case I can change the way we are installing GDAL in Travis CI to install a newer version. Can you check your local environment:

`pip freeze | grep GDAL`

**Comment by Sanazjd** [comment]
> @Sanazjd I finally got the C and Python GDAL packages to talk to each other!
> 
> There are some errors in the build log (https://travis-ci.org/danforthcenter/plantcv-hyperspectral/jobs/516307250). It looks like it doesn't like this:
> 
> ```python
> gdalhyper = gdal.Open(path)
> wavelength = gdalhyper.GetRasterBand(1)
> ```
> 
> `AttributeError: 'NoneType' object has no attribute 'GetRasterBand'`
> 
> One possibility is that this is a feature of GDAL v2+ and the Travis CI environment, using Ubuntu, is installing GDAL 1.11. If that is the case I can change the way we are installing GDAL in Travis CI to install a newer version. Can you check your local environment:
> 
> `pip freeze | grep GDAL`

My local GDAL version is 2.4.0, but now I'm getting the same error when I'm running tests.py. This error most probably refers to an incorrect path. But it worked properly with the same path before. I checked the data, and ran the function on jupyter locally without a problem though.

**Comment by nfahlgren** [comment]
Closing because the code was moved to danforthcenter/plantcv

**Pull request closed without merging**
