### PR TITLE
Hypernormal

### PR DESCRIPTION
**Pull request by Sanazjd**

### CODE REVIEW

**Comment by CJRobey** [comment]
I am currently using this to read in data. I would just note that the input is documented to require the path to the ".hdr" file, but that will fail. The path must be to the data file itself. This may be awaiting implementation, but in case it wasn't I wanted to let you all know.

**Comment by Sanazjd** [comment]
Caleb,
Correct, I just fixed it in the description.

**Comment by nfahlgren** [comment]
Whenever this is ready to merge let me know and I can approve the PR

**Comment by Sanazjd** [comment]
> Whenever this is ready to merge let me know and I can approve the PR

It is ready to merge.

**Review by nfahlgren — APPROVED** [review]
Thanks @Sanazjd!

**Pull request merged**
